### ISSUE TITLE
居然不给看了！

### ISSUE THREAD

**Issue by GZ-Metal-Cell** [promefire/promefire.github.io#1]
我最喜欢的博主弃坑了呜呜呜😭😭😭

**Comment by promefire** [comment]
出bug了😭


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: GZ-Metal-Cell ***@***.***&gt;
发送时间: 2023年12月20日 15:51
收件人: promefire/promefire.github.io ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[promefire/promefire.github.io] 居然不给看了！ (Issue #1)





 
我最喜欢的博主弃坑了呜呜呜😭😭😭

**Comment by GZ-Metal-Cell** [comment]
> 出bug了😭 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: GZ-Metal-Cell ***@***.***&gt; 发送时间: 2023年12月20日 15:51 收件人: promefire/promefire.github.io ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[promefire/promefire.github.io] 居然不给看了！ (Issue #1) 我最喜欢的博主弃坑了呜呜呜😭😭😭 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

promefire😭😭😭我的promefire😭😭😭
